### PR TITLE
Update loadContent.js

### PR DESCRIPTION
**Pull request by oyejateen**
Hey, İ have encountered an big bug with setup system due to which bot deletes the setup message in the server… so i have made some changes to fix that issue.
Feel free to contact me on discord :- ❀SUNSHİNE❀#1359[https://discord.com/users/890146474158075915]

### CODE REVIEW

**Comment by adh319** [comment]
i dont know if its a but or not, but i've faced this before the latest release. But, this bug u found is not on the setup channel ...i though. So the problem was on the mongodb server. You have to use local server instead of online server one.

**Comment by oyejateen** [comment]
Well, i tried both mongo and localhost. İ found no error in database it was working pretty well with it. İ have gone through the code and found error in content. Let me explain ya. So, there the error was instead of using a timeout, interaction deleteReply, our code was having ` if (message.author.id === client.user.id) {
            await delay(3000);
            message.delete();
        }`
And this things were causing the problem in the function. So, i have just rewrite it with interaction things and now it's working better.

So, it should be a bug right?

**Comment by adh319** [comment]
u may actually wanna see this https://github.com/Adivise/NanoSpacePlus/issues/14. << is this what u faced with the setup channel?

**Comment by oyejateen** [comment]
Actually, i faced same problem but i found the bug and fixed it and now the setup system actually works with mongo db. This is a pull request not an issue… you may try it with localhost or mongo db, it will work perfectly fine.

**Comment by adh319** [comment]
Mine is working fine btw without any change. Only migrate from using online mongo db to mongo local db.

**Comment by AADI0009** [comment]
> Actually, i faced same problem but i found the bug and fixed it and now the setup system actually works with mongo db. This is a pull request not an issue… you may try it with localhost or mongo db, it will work perfectly fine.

wtf u even trying to do?

**Comment by TEDDY6969** [comment]
Your mom

**Comment by oyejateen** [comment]
NVM i am closing the pr

**Pull request closed without merging**
